version: '3.8'

services:
  mongo1:
    image: mongo:4.4.7
    container_name: mongo1
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster

  mongo2:
    image: mongo:4.4.7
    container_name: mongo2
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    networks:
      - mongo-cluster

  mongo3:
    image: mongo:4.4.7
    container_name: mongo3
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    networks:
      - mongo-cluster

  setup:
    image: mongo:4.4.7
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    restart: "no"
    entrypoint: [ "bash", "-c", "sleep 10 && mongosh --host mongo1:27017 /docker-entrypoint-initdb.d/replica-init.js" ]
    volumes:
      - ./replica-init.js:/docker-entrypoint-initdb.d/replica-init.js
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge
